spring:
  application:
    name: rabbit-mq-crud
  datasource:
    url: jdbc:h2:mem:db_rabbit
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration"
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8383